### PR TITLE
Update RNUnityView.mm

### PR DESCRIPTION
**Pull request by jb-san**
Make it work with xcode 16

### CODE REVIEW

**Review by TruAmbition — APPROVED** [review]
Tested new changes confirmed working, fixed build errors for Xcode 16.

Rig Config:
Mac OS v15.0 
Arm64
Xcode v16.0

**Review by TruAmbition — APPROVED** [review]
The latest update to the PR that does the conditional logic for debug or release builds fixed this issue for me. I don't even have to go back and edit the UnityFramework.framework file like I did prior to the latest PR revision. Here are my test checkout as follows:

Intel (2017 iMac Pro)
- New Project -> 100/100 (Debug/Release) working
- Existing Project -> 0/0 (Debug/Release) working

Silicon (2022 M2 Air)
- New Project -> 100/100 (Debug/Release) working
- Existing Project -> 100/100 (Debug/Release) working

**Comment by wolfdavo** [comment]
Would love to get this merged asap - currently blocking prod development.

**Comment by TruAmbition** [comment]
> I can confirm that this works as well. Would love to see it merged.
> 
> 
> 
> Unity 6
> 
> ReactNative: 0.75.4

Thanks for doing a Checkout for Unity6. If you could confirm your Xcode version that would be helpful as well.

**Comment by konsnos** [comment]
> > I can confirm that this works as well. Would love to see it merged.
> > Unity 6
> > ReactNative: 0.75.4
> 
> Thanks for doing a Checkout for Unity6. If you could confirm your Xcode version that would be helpful as well.

Of course. 
Mac OS version 15.1.1
XCode version 16.1.

As a side note, I also tried building to a Mac with cocoapods version 1.14.* and it failed with some error about failed linking CoreAudioTypes.
cocoapods versions 1.15.2 and 1.16.2 work.

**Comment by TruAmbition** [comment]
Perfect! Thank you. Major 🔑 with the cocoapods note. 🦾

**Pull request merged**
